### ISSUE TITLE
progressive enhancement

### ISSUE THREAD

**Issue by delray** [HyperGAN/HyperGAN#117]
Could anyone share precisely how to use the 'progressive enhancement' feature and how it works?

**Comment by martyn** [comment]
Missed this one.  It's currently broken, sorry.  It is custom research we plan to re-add(and measure).

**Comment by martyn** [comment]
This is now just a custom config, and it's progressive enhancement does not give as large an improvement as it used to now that training is stabler. Going to mark this as fixed in 1.0.
