### ISSUE TITLE
Not Converging for 2D Test

### ISSUE THREAD

**Issue by superpirson** [HyperGAN/HyperGAN#140]
So I have pulled from the GitHub master and I have been running 
`python 2d-distribution.py train --sample_every 10000`
and after waiting a good 10 min or so, I get results like this: 
![image](https://user-images.githubusercontent.com/5897642/29473807-276915a2-8427-11e7-8a6e-ce98bf80c6c3.png)
![image](https://user-images.githubusercontent.com/5897642/29473855-5b8caa4c-8427-11e7-8637-57865f19f112.png)

While my system is not exactly top of the line right now, I have also been running this on my desktop with a GTX 980, to a similar effect. Am I just not giving it enough time, or is there something up here?

**Comment by martyn** [comment]
The default configuration is probably broken for that example.  We're still trying to find a set of hyperparams that work across problems.

**Comment by superpirson** [comment]
Ah. Well then do you know a configuration and problem that work? I tried a most of them with the 2d distribution and cannot get much to happen.

**Comment by martyn** [comment]
Reopening to answer once there's a stable configuration.

**Comment by martyn** [comment]
This is fixed in 1.0
