### ISSUE TITLE
Documentations on Command Line Usage

### ISSUE THREAD

**Issue by UltimatePea** [HyperGAN/HyperGAN#158]
Are there any detailed documentations on how to use HyperGAN from command line?

Specifically,

+ how to continue training using a saved file
+ how to load saved model for deployment
+ what are the arguments to "build" "sample"

The default argument prompt is unclear about those.

**Comment by martyn** [comment]
* Continuing training is as simple as rerunning the `train` command after saving.  You can try `--save_every 10` to test it out.
* `build` is very beta at the moment.  It should take the same arguments as `train`.  It builds a pbgraph which can be loaded(with lots of work right now).
* `sample` should also look the same as `train`.  It can include an additional flag `--sampler`.  You might also want `--save_samples`

I'll close this issue once we document things a little better. 

Thanks for the questions and happy to hear suggestions for the next release.

**Comment by martyn** [comment]
This is an ongoing effort but 1.0 is much better than before.
