### ISSUE TITLE
Its not letting me train 

### ISSUE THREAD

**Issue by EXOTIKIAN** [HyperGAN/HyperGAN#162]
@martyn This has been happening for ages i wanna know how to fix it i use ubuntu for it heres a screenshot for what im talking about
(https://user-images.githubusercontent.com/32023546/31523577-e9c5e17e-af8e-11e7-94fb-91c1127e4cf8.png)

if you can get back to me soon

**Comment by davidaylaian** [comment]
@EXOTIKIAN you need to specify the model you want to use with `-c`

**Comment by davidaylaian** [comment]
@EXOTIKIAN Did you run `hypergan new hypegan` to create the model you're trying to use?

**Comment by martyn** [comment]
This is the second ticket in the backlog around that error message. We should improve the error.

**Comment by martyn** [comment]
This actually works better in 1.0, closing
