### ISSUE TITLE
Can someone generate for me a good image?

### ISSUE THREAD

**Issue by symvizan** [HyperGAN/HyperGAN#164]
Hello.
I have a low end graphics card, and I can't generate a 256x256 photo.

I however need a photo with the following requirements:
 - it should be a face of a man
 - a non-existant man 
 - 256x256
 - realistic looking
 - only I get to use the photos so it won't ever be published on the internet or shared by the person who generated it

If someone could send me some pictures which I can select my photo from, I would really apprichiate it!
Thank you.

**Comment by aDotInTheVoid** [comment]
@symvizan, why not run it on aws ec2.

**Comment by martyn** [comment]
We will be releasing a face model for anyone to use with the 1.0 release.
