### ISSUE TITLE
content = open(filename)

### ISSUE THREAD

**Issue by AdamWarn** [HyperGAN/HyperGAN#170]
when running:
hypergan train folder/hypergan/Pokemon/pokemon/main-sprites -s 32x32x3 -f png -c mymodel --resize
in ubuntu to train hypergan it starts of just fine but after a second  i givs me the error:
File "/usr/local/bin/hypergan", line 67, in <module>
    config = hc.Selector().load(config_filename)
  File "/usr/local/lib/python3.5/dist-packages/hyperchamber/selector.py", line 112, in load
    content = open(filename)
TypeError: invalid file: None
and just stops.
i followed the install guide.
i am new to hypergan an ubuntu in general but found hypergan so intresting that i relly wanted to use it so all help is aprechiated.
sry for bad spelling.

**Comment by AdamWarn** [comment]
Oh i tried running it all as root to but it didnt make a difrence

**Comment by martyn** [comment]
This happens when the config file does not exist. Try a `hypergan new` first. Also we're close to releasing 1.0 which should give MUCH better results.
