### ISSUE TITLE
Running HyperGAN on Windows as a Newbie

### ISSUE THREAD

**Issue by Cooly568** [HyperGAN/HyperGAN#173]
I realize this is extremely unlikely to be fault of the program and more the fault of me, the user, but I am attempting to run HyperGAN on Windows 10 following @europax 's [ guide here. ](https://github.com/255BITS/HyperGAN/issues/72)

I have limited experience using Python, so while it has been an adventure, it hasn't been a very successful one.

I have managed to install TensorFlow-GPU, HyperGAN, and all its dependencies through Powershell, and even creating a virtual environment to run Hypergan within.

Where it starts to fall apart, is when I issue the hypergan command through Powershell...
![90221be537fbf3b3c268ef596cb3ccde](https://user-images.githubusercontent.com/3150204/42074089-e5a303fc-7b2f-11e8-8903-5270ed71d998.png)

...Windows pops up asking me what program I'd like to execute the command through
![untitled](https://user-images.githubusercontent.com/3150204/42074113-0efd6030-7b30-11e8-806d-b79319f84ee4.png)

Choosing Windows Powershell results in Powershell opening and quickly closing with no text.

Choosing python.exe results in what I believe to be the HyperGAN window opening up for a split second, before it closes quickly, citing "error: the following arguments are required: method"
![grasf](https://user-images.githubusercontent.com/3150204/42074259-cdb12d4a-7b30-11e8-98f4-835ef3cc35f1.png)

Now, calling HyperGAN with a command trailing it results in the same behavior. No matter what command it is, it will quit the exact same way with the exact same message.
![90221be537fbf3b3c268ef596cb3ccde](https://user-images.githubusercontent.com/3150204/42074153-507e8a02-7b30-11e8-9d64-0d3e78dbc16e.png)

Europax's guide stated that he had trouble making the hypergan command that I was using work, and chose to directly reference HyperGAN by calling python and then HyperGAN's directory, trying this myself resulted in Python being unable to find "__main__" module, a file HyperGAN does not have.

![1c699184772ca09ce5528c03aefe3866 1](https://user-images.githubusercontent.com/3150204/42074261-d17426e4-7b30-11e8-941d-c0a6e9162ff6.png)

Being a novice who doesn't know any better, I tried creating a copy of __init__ and renaming it __main__. This resulted in the following behavior.
![cbdce883ebe8c02617d302c37db287eb](https://user-images.githubusercontent.com/3150204/42074279-e7b7c604-7b30-11e8-8e49-592adcc76326.png)

So I'm at a loss on how to begin to either fix it or make HyperGAN run. As I'm a novice attempting this on a subject without many tutorials, I don't have many places to turn for help, and I don't know what I'm doing wrong.

**Comment by qwazwsx** [comment]
try the following

`python C:\Users\mhank\AppData\Local\Programs\Python\Python36\Scripts\hypergan new mymodel`

your problem is that `...Python36\lib\site-packages\hypergan` is a folder and not a file. If you run python with a folder it will return the `can't find '__main__' module` error.

**Comment by martyn** [comment]
All of these instructions will change and hopefully be much easier in 1.0.
After 1.0 we are planning to release a windows installer to simplify this.
