### ISSUE TITLE
Possible to use multiple classification

### ISSUE THREAD

**Issue by cppietime** [HyperGAN/HyperGAN#176]
I may not be using the proper terminology, but in the main readme, supervised learning with a classifier is mentioned. The example given is using an "apples" class and an "oranges" class. I'm looking to see if there is a way to classify data in more than one way. For example, instead of only separating data into apples and oranges, set up HyperGAN to also classify data to either "ripe" or "unripe". Is this possible, or am I misunderstanding how HyperGAN works?

**Comment by martyn** [comment]
This is the right idea but the implementation is changing in 1.0. Classification has multiple ways of being done. A tutorial is on the roadmap, there's a classifier example in develop if you are interested.
