### ISSUE TITLE
HyperGAN Windows Error

### ISSUE THREAD

**Issue by HonoriaS1** [HyperGAN/HyperGAN#178]
When I use europax's [directions to use hyperGAN](https://github.com/255BITS/HyperGAN/issues/72) on Windows 10 it gives "ModuleNotFoundError: No module named 'hypergan.cli'; 'hypergan' is not a package".

I would appreciate any information that could help fix this error. Thanks in advance!

**Comment by qwazwsx** [comment]
make sure that you do `pip3 install hypergan`

**Comment by Snaperkids** [comment]
I'm having the same problem. I've installed with pip3 and modified the cli.py file as described and I'm still getting the same error message.

**Comment by RChopin** [comment]
Referring to the directory helped for me
ex. C:\Users\[user]\AppData\Local\Programs\Python\Python36\Scripts\hypergan train ...

**Comment by martyn** [comment]
This is going to hopefully be fixed in 1.0.
