### ISSUE TITLE
Defining configuration location creates "NoneType" error

### ISSUE THREAD

**Issue by ThomasWarnasch** [HyperGAN/HyperGAN#179]
I've recently gotten HyperGAN to largely function correctly. The only problem left I have is that I'm unable to correctly set the config file location.

Running ``python C:\Users\Thomas\PycharmProjects\Tensorflow\venv\Scripts\hypergan train 256xfaces/ -s 256x256x3 -f png -b 16 --sample_every 100 --save_samples --config C:\Users\Thomas\Desktop\Test\hypergan\mymodel.json`` 

prompts the error

 ``File "C:\Users\Thomas\PycharmProjects\Tensorflow\venv\Scripts\hypergan", line 67, in <module>``
    ``config = hc.Selector().load(config_filename)``
  ``File "C:\Users\Thomas\Anaconda3\lib\site-packages\hyperchamber\selector.py", line 112, in load
    content = open(filename)``
``TypeError: expected str, bytes or os.PathLike object, not NoneType``

I've been able to run the same command without the config location set and it runs as intended and have ran the program as admin and it doesn't remove the error.

My personal guess is that for some unknown reason the config location doesn't properly recognize the file (located and named the exact same).

Thank you for your time. Hopefully we'll be able to get this figured out.

**Comment by ThomasWarnasch** [comment]
Config file must be located in "C:\Users\Thomas\Anaconda3\Lib\site-packages\hypergan\configurations\" when you install under Anaconda and you only use the file name without the extension ex. mymodel  or 
```python C:\Users\Thomas\PycharmProjects\Tensorflow\venv\Scripts\hypergan train 256xfaces/ -s 256x256x3 -f png -b 16 --sample_every 100 --save_samples --config mymodel```

**Comment by martyn** [comment]
Local config files should work(same directory as hypergan runs from). Now that we have a UI it'd be cool to load a config there, it's on the roadmap.
