### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by Zigler21** [HyperGAN/HyperGAN#182]
When I run Hypergan, It gives me the error: ModuleNotFoundError: No module named 'numpy'
The thing is, I already have numpy 
any ideas?

**Comment by MaffooBristol** [comment]
What is the output of `pip3 list | grep numpy`?

**Comment by jsrobson10** [comment]
Is it possible that you have numpy installed on one version of python but not the other? Try <code>pip install numpy</code> and <code>pip3 install numpy</code>.

**Comment by martyn** [comment]
Let us know if this is still an issue in 0.10
