### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by Airscrach** [HyperGAN/HyperGAN#187]
every time i try to install it i get this:
me=pip3 install hypergan --upgrade
SyntaxError: invalid syntax
 the word install is highlighted

any ideas?

**Comment by atomfero** [comment]
mine installs it but when i type in hypergan NOTHIN plus if i try python hypergan it says can't find '__main__' module in 'hypergan'

**Comment by MaffooBristol** [comment]
What's the output of `pip3 --version`?

**Comment by kabob8933** [comment]
Are you running this in a python3 shell or a terminal? It seems you are in a python3 shell when you need to be in a terminal.

**Comment by martyn** [comment]
Closing this and clarifying the docs in the next version.
