### ISSUE TITLE
Setting up hypergan with a local python directory

### ISSUE THREAD

**Issue by brucdarc** [HyperGAN/HyperGAN#188]
I'm trying to get hypergan working on my universities computers, and I have to install it to a local directory since I don't have permission to access the regular python directory. 
I have my path set up to include my local directory with python and other packages.

I used this command for installation

`pip3 install --ignore-installed --install-option="--prefix=/s/bach/g/under/cutreap/Desktop/hypergan/projpack" hypergan --upgrade --force-reinstall
`

I have been able to install hypergan with no problems, but when I try to run the `hypergan -h` command I get the error: 
`
Traceback (most recent call last):
  File "/s/bach/g/under/cutreap/Desktop/hypergan/projpack/bin/hypergan", line 6, in <module>
    import hyperchamber as hc
ModuleNotFoundError: No module named 'hyperchamber'
`

I've been trying to install hyperchamber manually

`pip3 install --ignore-installed --install-option="--prefix=/s/bach/g/under/cutreap/Desktop/hypergan/projpack" hyperchamber --upgrade --force-reinstall`

The install ends with a failure message of 

`error: /s/bach/g/under/cutreap/Desktop/hypergan/projpack/lib/python3.6/site-packages/urllib3/packages/__pycache__/six.cpython-36.pyc is a symlink and will be changed into a regular file if import writes a byte-compiled file to it
    

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-06n7a9xa/urllib3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wide0qh4-record/install-record.txt --single-version-externally-managed --compile --prefix=/s/bach/g/under/cutreap/Desktop/hypergan/projpack" failed with error code 1 in /tmp/pip-build-06n7a9xa/urllib3/
`

Any ideas of how to get the install to work?

**Comment by martyn** [comment]
Sorry for this issue. This should be fixed in the next version as we're removing this dependency.
