### ISSUE TITLE
When I type "hypergan test" into my Python 3.5 shell it says "invalid syntax"

### ISSUE THREAD

**Issue by nano38** [HyperGAN/HyperGAN#221]
Hi, I'm using hypergan on Windows. I know hypergan is not supported on Windows but I found this work around on an issue on this repository. It used to just not import, but now it does. I typed in "hypergan test" like what it said to do on the "Testing the install" section on the readme. After I type it in it says, "invalid syntax", and then it highlights "test". I have know idea what to do. I want to get it working on Windows rather then Linux, so I don't have to get my Linux machine up and running again. So, if anyone can offer any help that would be nice.

**Comment by mikkel** [comment]
I do not have windows running hypergan but there are some users in the [discord](https://discord.gg/t4WWBPF) that have had success.
You probably need to install 0.10, which is different than the old version in PIP
