### ISSUE TITLE
class loss is broken

### ISSUE THREAD

**Issue by mikkel** [HyperGAN/HyperGAN#230]
From discord:

guy
is --classloss broken?  (Gives error about missing .y from image loader)

Classloss is broken and needs to be revisited.  https://arxiv.org/abs/1610.09585 AC-GAN is probably a good place to start.

**Comment by martyn** [comment]
Honestly `--classloss` is not a great abstraction. It seems like different GANs can handle this different ways.
One of the recently added examples turns the generator into a classifier such that G(x) -> class and optimizes D((x, class), (x, G(x)).  There's a bunch of other ways to do this as well.

Let's just remove --classloss and give access to the GAN object about multiple input sources(`-a`).
