### ISSUE TITLE
Warning: no default GPU device available

### ISSUE THREAD

**Issue by MasterCubo** [HyperGAN/HyperGAN#241]
After running into "no module named 'hyperchamber'" and following your instructions on other issues, I ran into "no module named 'natsort'" then pillow, then nashpy. I did the same `pip3 install (missing module) --upgrade --force-reinstall` after that, I ran the first `hypergan test` that had no missing modules. I got a different error. Here is everything that happened after i typed that in.
`NAME-iMac:~ NAME$ hypergan test
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Loading configuration /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hypergan/configurations/default.json
Hooray!
Hypergan is installed correctly.  Testing tensorflow for GPU support.
WARNING:tensorflow:From /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hypergan/cli.py:215: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Warning: no default GPU device available
Default GPU Device: 
Current available tensorflow devices:
_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 17463133830046152813)
There were errors in the test, please see the logs`

Can you please help? I can show you the logs if you want.

**Comment by MasterCubo** [comment]
Is it a problem with the way I set up HyperGAN, my GPU, or tensorflow?

**Comment by ayunami2000** [comment]
im getting the same thing (the natsort dependency part), but I havent restarted yet after installing CUDA. im assuming itll probably fix for me after a restart, but i havent actually tried this yet.

**Comment by ayunami2000** [comment]
I found the solution: Just open Geforce Experience and update your drivers. It'll fix everything.

**Comment by MasterCubo** [comment]
I'm sorry, how do I open Geforce Experience? I'm on mac, by the way.

**Comment by MasterCubo** [comment]
I'm so dumb. Geforce Experience is a downloadable program.

**Comment by MasterCubo** [comment]
I have wine, but I'm getting an error saying "The operating system in use is not supported by this package" Which is obvious, but is there any way around it?

**Comment by ayunami2000** [comment]
that sounds like a different issue. you probably shouldnt get tensorflow GPU then and maybe itll work without GPU support. uninstall tensorflow-gpu. itll probably be considerably slower but it should work. (maybe)

**Comment by MasterCubo** [comment]
Result:
`WARNING: Skipping tensorflow-GPU as it is not installed.`

**Comment by MasterCubo** [comment]
I'll install tensorflow, which I thought I had, then uninstall tensorflow-GPU. It probably won't work but I'll try.

**Comment by MasterCubo** [comment]
I did it and got the same warning as before.

**Comment by MasterCubo** [comment]
Its obviously because I'm on mac though.

**Comment by martyn** [comment]
1.0 switches to pytorch so this error will change(although I'm unsure of status of pytorch on osx).
