### ISSUE TITLE
Hypergan Is Not a Package

### ISSUE THREAD

**Issue by dudeymopster** [HyperGAN/HyperGAN#244]
I run this command:
`hypergan test`
And get this back:
`  File "C:\Users\dusti\AppData\Local\Programs\Python37\Scripts\\hypergan", line 7, in <module>
    import hypergan as hg
  File "C:\Users\dusti\AppData\Local\Programs\Python37\Scripts\hypergan.py", line 8, in <module>
    import hypergan.cli as cli
ModuleNotFoundError: No module named 'hypergan.cli'; 'hypergan' is not a package`

I have literally installed all requirements, they are working perfect. This is so damn frustrating.

**Comment by martyn** [comment]
Sorry for the frustration. The dependencies on hypergan made it tough to install, one of the main drivers for switching to pytorch. This should be fixed in 1.0 when it's released.
