### ISSUE TITLE
Attempting to run the Sampler command gives "ValueError: need at least one array to concatenate"

### ISSUE THREAD

**Issue by catyoop** [HyperGAN/HyperGAN#246]
I'm not sure if I'm just using the commands wrong or if theres an issue with the samplers, I trained using the default config on a dataset of 256x256 pngs, it trained for 17k iterations, that worked fine.

Using Static_batch works fine but it only gives a static snapshot, the walk samplers don't seem to work. 

Random_walk gives:
 "AttributeError: 'ImageLoader' object has no attribute 'set'"

**The command I gave to train it initally:** 
"hypergan train -s 256x256x3 -f png -b 32 --config default --resize --crop --sampler static_batch --sample_every 1 --save_samples --save_every 1000 /home/catyoop/Documents/256png2"

**This is an example of on of the commands I used to try to get the sampler to work:**
"hypergan sample /home/catyoop/Documents/256png2 -s 256x256x3 -f png -b 32 --config default --sampler batch_walk --sample_every 5 --save_samples"

**This is what I get when I ran the example sample attempt:**

Loading configuration /home/catyoop/Hypergan/orchido/default.json
[loader] ImageLoader found 5528
Shuffling data
2019-12-15 11:54:29.079918: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-15 11:54:29.116938: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x557494fd0160 executing computations on platform CUDA. Devices:
2019-12-15 11:54:29.117023: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-12-15 11:54:29.338349: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3605695000 Hz
2019-12-15 11:54:29.339192: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x557494fda8f0 executing computations on platform Host. Devices:
2019-12-15 11:54:29.339240: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-12-15 11:54:29.339864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 9.93GiB
2019-12-15 11:54:29.339901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-12-15 11:54:29.362616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-15 11:54:29.362660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-12-15 11:54:29.362678: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-12-15 11:54:29.363135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9658 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From /home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-12-15 11:54:29.381974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-12-15 11:54:29.382020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-15 11:54:29.382029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-12-15 11:54:29.382037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-12-15 11:54:29.382232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9658 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
class function:hypergan.distributions.uniform_distribution.UniformDistribution <class 'hypergan.distributions.uniform_distribution.UniformDistribution'>
class function:hypergan.generators.resizable_generator.ResizableGenerator <class 'hypergan.generators.resizable_generator.ResizableGenerator'>
WARNING:tensorflow:Variable *= will be deprecated. Use `var.assign(var * other)` if you want assignment to the variable value or `x = x * y` if you want a new python Tensor object.
Generator Architecture:
linear 4*4*512
resize_conv 512
resize_conv 256
resize_conv 128
resize_conv 64
resize_conv 32
resize_conv 3
class class:hypergan.discriminators.configurable_discriminator.ConfigurableDiscriminator <class 'hypergan.discriminators.configurable_discriminator.ConfigurableDiscriminator'>
number of params in layer  conv [32, ''] 896
number of params in layer  conv [64, ''] 18496
number of params in layer  conv [128] 73856
number of params in layer  conv [256] 295168
number of params in layer  conv [512] 1180160
number of params in layer  linear [1] 32768
class function:hypergan.losses.logistic_loss.LogisticLoss <class 'hypergan.losses.logistic_loss.LogisticLoss'>
prereg Tensor("add_20:0", shape=(32, 1), dtype=float32, device=/device:GPU:0)
class function:hypergan.trainers.batch_fitness_trainer.BatchFitnessTrainer <class 'hypergan.trainers.batch_fitness_trainer.BatchFitnessTrainer'>
class function:hypergan.trainers.simultaneous_trainer.SimultaneousTrainer <class 'hypergan.trainers.simultaneous_trainer.SimultaneousTrainer'>
C  [<tf.Variable 'Variable_1:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_2:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_3:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_4:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_5:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_6:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_7:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_8:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_9:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_10:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_11:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_12:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_13:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_14:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_15:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_16:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_17:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_18:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_19:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_20:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_21:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_22:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_23:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_24:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_25:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_26:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_27:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_28:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_29:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_30:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_31:0' shape=(1, 256, 256, 3) dtype=float32_ref>, <tf.Variable 'Variable_32:0' shape=(1, 256, 256, 3) dtype=float32_ref>] [<tf.Tensor 'split:0' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:1' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:2' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:3' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:4' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:5' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:6' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:7' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:8' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:9' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:10' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:11' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:12' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:13' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:14' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:15' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:16' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:17' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:18' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:19' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:20' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:21' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:22' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:23' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:24' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:25' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:26' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:27' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:28' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:29' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:30' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'split:31' shape=(1, 256, 256, 3) dtype=float32>]
WARNING:tensorflow:From /home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
[discriminator] Class loss is off.  Unsupervised learning mode activated.
[hypergan] |= Loading network from /home/catyoop/Hypergan/orchido/saves/default/model.ckpt
[hypergan] |= Loading checkpoint from /home/catyoop/Hypergan/orchido/saves/default
WARNING:tensorflow:From /home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Model loaded
WARNING:tensorflow:From /home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/hypergan/cli.py:208: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:`tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
z_INT (0,)
Traceback (most recent call last):
  File "/home/catyoop/anaconda3/envs/hypergan1.0/bin/hypergan", line 135, in <module>
    gancli.run()
  File "/home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/hypergan/cli.py", line 209, in run
    self.sample_forever()
  File "/home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/hypergan/cli.py", line 121, in sample_forever
    self.sample()
  File "/home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/hypergan/cli.py", line 76, in sample
    sample_list = self.sampler.sample(sample_file, allow_save and self.args.save_samples)
  File "/home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/hypergan/samplers/base_sampler.py", line 23, in sample
    sample = self._sample()
  File "/home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/hypergan/samplers/batch_walk_sampler.py", line 67, in _sample
    g = np.hstack(gs)
  File "/home/catyoop/anaconda3/envs/hypergan1.0/lib/python3.5/site-packages/numpy/core/shape_base.py", line 340, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: need at least one array to concatenate

**In case it helps heres the conda list for the env I'm running it in:**
conda list
# packages in environment at /home/catyoop/anaconda3/envs/hypergan1.0:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.8.1                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
bleach                    1.5.0                    pypi_0    pypi
ca-certificates           2019.10.16                    0  
certifi                   2018.8.24                py35_1  
chardet                   3.0.4                    pypi_0    pypi
gast                      0.3.2                    pypi_0    pypi
grpcio                    1.25.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
html5lib                  0.9999999                pypi_0    pypi
hyperchamber              0.2.8                    pypi_0    pypi
hypergan                  0.10.0                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markdown                  3.1.1                    pypi_0    pypi
mock                      3.0.5                    pypi_0    pypi
nashpy                    0.0.19                   pypi_0    pypi
natsort                   6.2.0                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.4                   pypi_0    pypi
openssl                   1.0.2t               h7b6447c_1  
pillow                    6.2.1                    pypi_0    pypi
pip                       10.0.1                   py35_0  
protobuf                  3.11.1                   pypi_0    pypi
pygame                    1.9.6                    pypi_0    pypi
python                    3.5.6                hc3d631a_0  
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   pypi_0    pypi
scipy                     1.3.3                    pypi_0    pypi
setuptools                40.2.0                   py35_0  
six                       1.13.0                   pypi_0    pypi
sqlite                    3.30.1               h7b6447c_0  
tensorboard               1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
tensorflow-gpu            1.13.1                   pypi_0    pypi
tensorflow-tensorboard    1.5.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
urllib3                   1.25.7                   pypi_0    pypi
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.31.1                   py35_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3

**Comment by martyn** [comment]
Should be fixed in 1.0 when it's released.
