### ISSUE TITLE
Transition to tensorflow.compat.v1 as tf, instead of tensorflow as tf

### ISSUE THREAD

**Issue by IIIBlueberry** [HyperGAN/HyperGAN#260]
this import change will allow Hypergan to works both on Tensorflow 2 and Tensorflow 1.14 and above which will solves issue #258 
https://www.tensorflow.org/api_docs/python/tf/compat#tensorflow_1x_and_2x_apis

**Comment by LivelyCarpet87** [comment]
This seems like a doable short term fix, yes, but I am uncertain how long that compatibility would be supported. It is after all harder to downgrade.

**Comment by IIIBlueberry** [comment]
> 
> 
> This seems like a doable short term fix, yes, but I am uncertain how long that compatibility would be supported. It is after all harder to downgrade.

AFIK the compatibility modules is here to stay, tensorflow 1.15 also included the TF 2.0 API which allowed you to write forward compatible code

> TensorFlow 1.15 contains a complete implementation of the 2.0 API in its compat.v2 module. It contains a copy of the 1.15 main module (without contrib) in the compat.v1 module. TensorFlow 1.15 is able to emulate 2.0 behavior using the enable_v2_behavior() function.
> This enables writing forward compatible code: by explicitly importing either tensorflow.compat.v1 or tensorflow.compat.v2, you can ensure that your code works without modifications against an installation of 1.15 or 2.0.

However with the hypergan develop branch it seems that hypergan author is transitioning to pytorch #259
