### ISSUE TITLE
[Documentation] Table of contents has dead links

### ISSUE THREAD

**Issue by jn4kr** [HyperGAN/HyperGAN#266]
Hi,

the links in readme are dead (e.g. https://github.com/HyperGAN/HyperGAN/blob/master/#quick-start). It's not a huge problem as the documentation is also under https://hypergan.gitbook.io/hypergan/ and everything can be still scrolled to, but i would suggest to fix it. 

Sry for the edit's accidentally hit send.

**Comment by AI-Spawn** [comment]
I opened a pull request to fix this. 
https://github.com/HyperGAN/HyperGAN/pull/270
