### ISSUE TITLE
Modifications to work in Windows?

### ISSUE THREAD

**Issue by DippedPretzels** [HyperGAN/HyperGAN#72]
I'm just curious how feasible you think it would be to get this running in Windows.  tf.contrib.ffmpeg ops aren't currently supported in Windows (is this only used for animation?), and neither is fcntl. flask, flask-cors, hyperchamber, tensorflow, scipy, and Pillow already work in Windows.

Great work by the way!

**Comment by DippedPretzels** [comment]
OK - I think I got it running.  I'll confirm by training a larger dataset over the weekend, but at least Improved-GAN is generating samples.

**Comment by martyn** [comment]
Thanks for testing on Windows.  Glad to know it's working!

**Comment by pavanagrawal123** [comment]
@DippedPretzels how did you get around the fcntl requirement?

**Comment by DippedPretzels** [comment]
I used the comment on this thread:[](
https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows)

You make a fcntl.py that contains:
```
def fcntl(fd, op, arg=0):
    return 0
        
def ioctl(fd, op, arg=0, mutable_flag=True):
    if mutable_flag:
        return 0
    else:
        return ""
    
def flock(fd, op):
    return
        
def lockf(fd, operation, length=0, start=0, whence=0):
    return`
```
and put in your PATH for python.  This worked for 0.8, and I'm trying to get 0.9 working in Windows, but samples don't seem to be saving (training appears to work though.)  It may be an issue with Windows and gi.repository.

**Comment by mikkel** [comment]
Samples don't save automatically now, use `--save_samples`.  This will probably make more sense once this is merged: https://github.com/255BITS/HyperGAN/pull/111

**Comment by europax** [comment]
I got HyperGAN to run on Windows 10 today, and here's the guide to do it:

1. Get Python 3.6.x, 64 bit (32 bit won't work; 64 bit is x86-64) from here: https://www.python.org/downloads/windows/
2. Follow the guide for Tensorflow GPU here: https://www.tensorflow.org/install/install_windows (CUDA Toolkit 9.0 and cuDNN v7.0. are required)
Here are the download links: 
CUDA Toolkit 9.0 - https://developer.nvidia.com/cuda-90-download-archive
cuDNN v7.0 - https://developer.nvidia.com/cudnn (you need to register first)
3. Launch PowerShell in admin mode - just right click the Windows icon/start button and click Windows PowerShell (Admin)
4. Install the dependencies for hypergan and hypergan itself:
pip3 install numpy tensorflow-gpu hyperchamber pillow pygame
pip3 install hypergan --upgrade
I recommend getting tensorflow-gpu 1.6.0 - I had issues with 1.7.0:
pip3 install tensorflow-gpu==1.6.0
5. Update cli.py like in #161 . cli.py is located here if you installed for all users: "C:\Program Files\Python36\Lib\site-packages\hypergan". You might need to copy/move the file to desktop/anywhere else, edit it and then copy/move it back.
6. Go to any folder you want to use HyperGAN in. It's possible to write hypergan as a command in PowerShell, but it didn't work for me, so when reading the guide on the main page, replace "hypergan" with the following:  
python 'C:\Program Files\Python36\Scripts\hypergan'

And an example of the full command usage would be:
hypergan new mymodel 
or
python 'C:\Program Files\Python36\Scripts\hypergan' new mymodel

I hope this helps!

**Comment by darthdeus** [comment]
@europax Thanks! Confirming that this works. I'm confused tho why can't we just run `python -m hypergan`?

**Comment by Airscrach** [comment]
i  tried to use @europax guide but i hit a wall with installing hypergan #187

**Comment by Milan12332567** [comment]
I got AMD Gpu; it wont work

**Comment by lcdavis13** [comment]
@europax Even after installing old versions of hypergan (0.9.0, 0.9.1, 0.9.5) it is always looking for CUDA 10 dlls for some reason. Hopefully I can get it to work with the latest CUDA...

**Comment by yaboy-withtheabbicus** [comment]
eat my butt

**Comment by martyn** [comment]
This will be simpler in 1.0. We're also planning a windows installer post 1.0.
